#!/bin/bash

# Check which Linux distribution the system is on
distro_info_raw=$(cat /etc/os-release)

if echo "$distro_info_raw" | grep -q "Ubuntu"; then
	echo "Running Ubuntu LAMP installer"
	./lamp_install_ubuntu
	# Run Ubuntu lamp installer
elif echo "$distro_info_raw" | grep -Eq "Red Hat|CentOS"; then
	echo "Running RHEL LAMP installer"
	./lamp_install_rhel
	# Run RHEL lamp installer
else
	echo "Your Linux distribution is not supported."
fi

